version: '3'

services:
  site:
    volumes:
      - .:/var/www/html
      - ./config/vhost.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - PROJECT_NAME=foobar
    ports:
      - 80:80
    build:
      context: .
      args:
        PROJECT_NAME: ${PROJECT_NAME}
